# Generated by Django 5.1.7 on 2025-03-15 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_uk', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('image', models.ImageField(upload_to='../static/img/football/countries/')),
            ],
            options={
                'verbose_name': 'Країна',
                'verbose_name_plural': 'Країни',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_uk', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('surname_uk', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('Воротар', 'ВРТ'), ('Лівий захисник', 'ЛЗ'), ('Центральний захисник', 'ЦЗ'), ('Правий захисник', 'ПЗ'), ('Опорний півзахисник', 'ЦОП'), ('Центральний півзахисник', 'ЦП'), ('Атакувальний півзахисник', 'ЦАС'), ('Лівий півзахисник', 'ЛП'), ('Правий півзахисник', 'ПП'), ('Лівий вінгер', 'ЛВ'), ('Правий вінгер', 'ПВ'), ('Нападник', 'НАП')], max_length=100)),
                ('birth_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='../static/img/football/players/')),
            ],
            options={
                'verbose_name': 'Гравець',
                'verbose_name_plural': 'Гравці',
            },
        ),
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_uk', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('image', models.ImageField(upload_to='../static/img/football/leagues/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.countries')),
            ],
            options={
                'verbose_name': 'Ліга',
                'verbose_name_plural': 'Ліги',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_uk', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('image', models.ImageField(upload_to='../static/img/football/teams/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.countries')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.leagues')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команди',
            },
        ),
    ]
