# Generated by Django 5.1.7 on 2025-03-15 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='rating_uefa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='countries',
            name='image',
            field=models.ImageField(upload_to='img/football/countries/'),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='football.countries'),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='image',
            field=models.ImageField(upload_to='img/football/leagues/'),
        ),
    ]
