# Generated by Django 5.1.7 on 2025-03-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_countries_rating_uefa_alter_countries_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=100)),
                ('text_uk', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='../static/img/football/news/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='countries',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/football/countries/'),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/football/leagues/'),
        ),
        migrations.AlterField(
            model_name='players',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='../static/img/football/players/'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='../static/img/football/teams/'),
        ),
    ]
