# Generated by Django 5.1.7 on 2025-03-16 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_alter_news_image_alter_players_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cups',
            name='name',
        ),
        migrations.RemoveField(
            model_name='leagues',
            name='name',
        ),
        migrations.RemoveField(
            model_name='players',
            name='name',
        ),
        migrations.RemoveField(
            model_name='players',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='name',
        ),
    ]
