# Generated by Django 5.1.7 on 2025-03-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_remove_teams_cup_teams_cups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='cups',
            field=models.ManyToManyField(blank=True, related_name='teams', to='football.cups'),
        ),
    ]
