# Generated by Django 5.1.7 on 2025-03-17 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_alter_teams_league_matches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='competition_id',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='competition_type',
        ),
        migrations.AlterField(
            model_name='matches',
            name='away_team_score',
            field=models.PositiveSmallIntegerField(default='-'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='home_team_score',
            field=models.PositiveSmallIntegerField(default='-'),
        ),
        migrations.CreateModel(
            name='MatchesCup',
            fields=[
                ('matches_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='football.matches')),
                ('cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cup', to='football.cups')),
            ],
            options={
                'verbose_name': 'Матч кубка',
                'verbose_name_plural': 'Матчі кубка',
            },
            bases=('football.matches',),
        ),
        migrations.CreateModel(
            name='MatchesLeague',
            fields=[
                ('matches_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='football.matches')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league', to='football.leagues')),
            ],
            options={
                'verbose_name': 'Матч ліги',
                'verbose_name_plural': 'Матчі ліги',
            },
            bases=('football.matches',),
        ),
    ]
