# Generated by Django 5.1.7 on 2025-03-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_remove_matches_competition_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='away_team_score',
            field=models.CharField(default='-', max_length=2),
        ),
        migrations.AlterField(
            model_name='matches',
            name='home_team_score',
            field=models.CharField(default='-', max_length=2),
        ),
    ]
