# Generated by Django 5.1.7 on 2025-03-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0010_alter_matches_away_team_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='away_team_score',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='home_team_score',
        ),
    ]
