# Generated by Django 5.1.7 on 2025-03-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0011_remove_matches_away_team_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='away_team_score',
            field=models.CharField(default='-', max_length=2),
        ),
        migrations.AddField(
            model_name='matches',
            name='home_team_score',
            field=models.CharField(default='-', max_length=2),
        ),
    ]
