# Generated by Django 5.1.7 on 2025-03-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0012_matches_away_team_score_matches_home_team_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='away_team_score',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='matches',
            name='home_team_score',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='matches',
            name='match_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='matches',
            name='status',
            field=models.CharField(default='SCHEDULED', max_length=20),
        ),
    ]
