# Generated by Django 5.1.7 on 2025-03-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0013_alter_matches_away_team_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchesleague',
            name='matches_ptr',
        ),
        migrations.RemoveField(
            model_name='matchescup',
            name='matches_ptr',
        ),
        migrations.RemoveField(
            model_name='matchescup',
            name='cup',
        ),
        migrations.RemoveField(
            model_name='matchesleague',
            name='league',
        ),
        migrations.DeleteModel(
            name='Matches',
        ),
        migrations.DeleteModel(
            name='MatchesCup',
        ),
        migrations.DeleteModel(
            name='MatchesLeague',
        ),
    ]
