# Generated by Django 5.1.7 on 2025-03-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0015_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='away_goals',
            field=models.CharField(default='-', max_length=2),
        ),
        migrations.AddField(
            model_name='matches',
            name='home_goals',
            field=models.CharField(default='-', max_length=2),
        ),
        migrations.AddField(
            model_name='matches',
            name='status',
            field=models.CharField(choices=[('Запланований', 'Scheduled'), ('Завершений', 'Finished')], default='Запланований', max_length=15),
        ),
    ]
