# Generated by Django 5.1.7 on 2025-03-17 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('football', '0016_matches_away_goals_matches_home_goals_matches_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matches',
            options={'verbose_name': 'Матч', 'verbose_name_plural': 'Матчі'},
        ),
        migrations.AddField(
            model_name='matches',
            name='competition_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='matches',
            name='competition_type',
            field=models.ForeignKey(default=1, limit_choices_to={'model__in': ('leagues', 'cups')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
    ]
