# Generated by Django 5.1.7 on 2025-03-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0017_alter_matches_options_matches_competition_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='cups',
        ),
        migrations.AlterModelOptions(
            name='matches',
            options={'ordering': ['match_date', 'match_time'], 'verbose_name': 'Матч', 'verbose_name_plural': 'Матчі'},
        ),
        migrations.RemoveField(
            model_name='matches',
            name='competition_id',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='competition_type',
        ),
        migrations.AddField(
            model_name='leagues',
            name='tournament_format',
            field=models.CharField(choices=[('Ліга', 'League'), ('Кубок', 'Cup'), ('Міксований', 'Mixed')], default='Ліга', max_length=100),
        ),
        migrations.RemoveField(
            model_name='teams',
            name='league',
        ),
        migrations.DeleteModel(
            name='Cups',
        ),
        migrations.AddField(
            model_name='teams',
            name='league',
            field=models.ManyToManyField(related_name='teams', to='football.leagues'),
        ),
    ]
