# Generated by Django 5.1.7 on 2025-03-17 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0018_remove_teams_cups_alter_matches_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='football.leagues'),
        ),
    ]
