# Generated by Django 5.1.7 on 2025-03-17 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0019_matches_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='status',
        ),
    ]
