# Generated by Django 5.1.7 on 2025-03-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0020_remove_matches_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='status',
            field=models.CharField(default='Заплановані', max_length=20),
        ),
    ]
