# Generated by Django 5.1.7 on 2025-03-18 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0022_remove_matches_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='surname_uk',
        ),
        migrations.AddField(
            model_name='players',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='football.countries'),
        ),
        migrations.AddField(
            model_name='players',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='football.teams'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='country',
            field=models.ForeignKey(default='Англія', on_delete=django.db.models.deletion.CASCADE, to='football.countries'),
        ),
    ]
