# Generated by Django 5.1.7 on 2025-03-19 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0023_remove_players_surname_uk_players_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='status',
            field=models.CharField(choices=[('Запланований', 'Planned'), ('Завершений', 'Finnished')], default='Запланований', max_length=20),
        ),
        migrations.AlterField(
            model_name='teams',
            name='country',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='football.countries'),
        ),
    ]
