# Generated by Django 5.1.7 on 2025-04-10 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0024_matches_status_alter_teams_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='matches_round',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='matches',
            name='status',
            field=models.CharField(choices=[('Запланований', 'Planned'), ('Завершений', 'Finished')], default='Запланований', max_length=20),
        ),
        migrations.AlterField(
            model_name='teams',
            name='country',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='football.countries'),
        ),
    ]
