# Generated by Django 5.1.7 on 2025-04-10 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0025_matches_matches_round_alter_matches_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='matches_round',
        ),
    ]
