# Generated by Django 5.1.7 on 2025-06-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0026_remove_matches_matches_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('FINISHED', 'Finished')], default='PLANNED', max_length=20),
        ),
    ]
